vim.tbl_map(
  function(p)
    vim.g["loaded_" .. p] = vim.endswith(p, "provider") and 0 or 1
  end,
  {
    "2html_plugin",
    "gzip",
    "matchit",
    "netrw",
    "netrwPlugin",
    "perl_provider",
    "python_provider",
    "tar",
    "tarPlugin",
    "vimball",
    "vimballPlugin",
    "zip",
    "zipPlugin",
  }
)
